const app=document.getElementById('app');const cache=new Map();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(s)=>`#/surah/${s}`;
async function get(n){if(!cache.has(n)){const r=await fetch(`/data/surah-${String(n).padStart(2,'0')}.json`);if(!r.ok)throw Error('Data unavailable');cache.set(n,await r.json())}return cache.get(n)}
function card(r){return `<article class="record"><div><span class="badge">${esc(r.namespace)}</span><span class="badge">${esc(r.kind)}</span><span class="badge">${esc(r.researchState)}</span>${r.open?'<span class="badge">OPEN</span>':''}</div><h3><a href="#/record/${encodeURIComponent(r.slug)}">${esc(r.id)} — ${esc(r.title)}</a></h3><p class="muted">${esc(r.verse||'')} · ${esc(r.role||'')}</p></article>`}
async function home(){let m=await(await fetch('/data/source-manifest.json')).json();app.innerHTML=`<h2>Published research: Surahs 1–12</h2><p>Research publication approved by the project owner. Original research-state and source metadata are preserved; OPEN and REVERIFY remain unresolved.</p><div class="cards">${m.surahs.map(s=>`<a class="card" href="${link(s.surah)}"><strong>Surah ${s.surah}: ${esc(s.name)}</strong><p>${s.verseCount} verses · ${s.records} research records</p><small>${s.chatgpt} ChatGPT · ${s.grok} Grok · ${s.open} open</small></a>`).join('')}</div>`}
async function surah(n){const s=await get(n);app.innerHTML=`<p><a href="#/">← All Surahs</a></p><h2>Surah ${s.surah}: ${esc(s.name)}</h2><p>${s.verseCount} verses · ${s.records.length} research records · Original source classifications preserved</p><div class="controls"><input id="search" aria-label="Search records" placeholder="Search title, ID, verse or text"><select id="kind"><option value="">All record types</option>${[...new Set(s.records.map(r=>r.kind))].sort().map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="origin"><option value="">Both research origins</option><option value="chatgpt">ChatGPT</option><option value="grok">Grok</option></select></div><p id="count"></p><section id="records"></section>`;
const search=document.getElementById('search'),kind=document.getElementById('kind'),origin=document.getElementById('origin');function show(){let q=search.value.toLowerCase().trim();let a=s.records.filter(r=>(!kind.value||r.kind===kind.value)&&(!origin.value||r.namespace===origin.value)&&(!q||[r.id,r.title,r.verse,...(r.bodyParagraphs||[])].join(' ').toLowerCase().includes(q)));document.getElementById('count').textContent=`Showing ${a.length} of ${s.records.length} records`;document.getElementById('records').innerHTML=a.slice(0,250).map(card).join('')+(a.length>250?'<p>Showing first 250 matches. Narrow your search to see more.</p>':'')}search.oninput=kind.onchange=origin.onchange=show;show()}
async function record(slug){let m=await(await fetch('/data/source-manifest.json')).json(),n=m.slugs[slug];if(!n){app.textContent='Record not found';return}let s=await get(n),r=s.records.find(x=>x.slug===slug);if(!r){app.textContent='Record not found';return}app.innerHTML=`<p><a href="${link(n)}">← Surah ${n}</a></p><h2>${esc(r.id)} — ${esc(r.title)}</h2><p><span class="badge">${esc(r.namespace)}</span><span class="badge">${esc(r.kind)}</span><span class="badge">Research: ${esc(r.researchState)}</span>${r.open?'<span class="badge">OPEN</span>':''}</p><p>Verse: ${esc(r.verse)}</p><section class="panel"><h3>Original research record</h3>${(r.fields||[]).map(f=>`<p><strong>${esc(f.label)}:</strong> ${esc(f.value)}</p>`).join('')}${(r.bodyParagraphs||[]).map(p=>`<p>${esc(p)}</p>`).join('')}</section><details><summary>Source provenance</summary><pre>${esc(JSON.stringify(r.source||{},null,2))}</pre></details><p class="muted">Research status and source publication metadata reflect the original export. Public inclusion was separately approved for Surahs 1–12.</p>`}
function about(){app.innerHTML=`<h2>About this publication</h2><p>This independent, read-only website publishes the research data present in the supplied Grok workspace for Surahs 1–12, as approved by the project owner. Both ChatGPT and Grok findings retain separate attribution.</p><p>OPEN/REVERIFY findings remain open. The research text has not been rewritten for publication. Original embedded DRAFT/UNPUBLISHED metadata remain visible where present because they describe the source export, not this subsequent publication approval.</p><p><strong>Coverage limitation:</strong> This first deployment is a QDISC/QB-focused research reader. It does not yet represent all sixteen cumulative research components as independently navigable registers. Source-to-frozen-record fidelity has not been certified field by field.</p><p>No AI subscription, sign-in, or external database is required to serve this website.</p>`}
async function route(){try{let a=decodeURIComponent(location.hash.slice(2)).split('/');if(a[0]==='surah'&&/^([1-9]|1[0-2])$/.test(a[1]))await surah(Number(a[1]));else if(a[0]==='record'&&a[1])await record(a.slice(1).join('/'));else if(a[0]==='about')about();else await home()}catch(e){app.textContent='Unable to load the research data: '+e.message}}window.addEventListener('hashchange',route);route();
